### PR TITLE
use latest pip on travis and enable caching

### PR DESCRIPTION
**Pull request by thijstriemstra**
- also builds docs and does some pep8 checks on travis
- moved version number to central place in `flickrapi/__version__.py`
- lots of pep8 fixes (whitespace, missing lines etc)
- bump version to 2.3.2

### CODE REVIEW

**Comment by thijstriemstra** [comment]
This PR seems to reveal some test failures and broken coverage report:

```
Coverage.py warning: No data was collected. (no-data-collected)
```

**Comment by thijstriemstra** [comment]
ping @sybrenstuvel (you should enable github feature 'request review' for prs).

**Comment by sybrenstuvel** [comment]
I could make you collaborator, so that you can do that yourself. Would you like that?

**Comment by thijstriemstra** [comment]
sounds good, thx.

**Comment by sybrenstuvel** [comment]
Nice work!

The `requirements.txt` file contains the exact versions of all the dependencies I use for testing, and provides a known-good set of version numbers. This also makes it possible to have multiple machines (owned by the same or different developers) all with a consistent set of dependencies. As such, it can't be replaced by just the version numbers in `setup.py` (which indicate minimum versions and/or upper limits to the versions for compatibility reasons, but not specific version numbers).

I do agree that those versions should be updated at some point.

**Comment by thijstriemstra** [comment]
I will define the latest and greatest in setup.py then?

**Comment by sybrenstuvel** [comment]
No, define the minimum required versions in the `setup.py`. Don't increase them unless there is a very good reason to. Having those versions as low as possible makes it much easier for packaging with Linux distributions, 3rd party applications, etc. as they don't have to mess with their other packages when pulling in an update to the FlickrAPI library.

**Comment by thijstriemstra** [comment]
@sybrenstuvel pinned the versions in setup.py

**Comment by sybrenstuvel** [comment]
I may not have been clear in my explanation. The versions should be mimimal versions, i.e. `pkgname>=2.4`, so that newer versions that have already been installed are also valid. `requirements.txt` should contain specific versions, i.e. `pkgname==2.4`.

**Comment by sybrenstuvel** [comment]
(version numbers there are for illustration only, they could very well be different)

**Comment by thijstriemstra** [comment]
@sybrenstuvel gotcha, see update.

**Comment by sybrenstuvel** [comment]
Better, but why still delete `requirements.txt`?

In `travis.yml` you put `pip install --ignore-installed --upgrade setuptools pip tox-travis coveralls`. What's the effect of having both `--ignore-installed` and `--upgrade` in one invocation? Don't they clash?

**Pull request merged**
