### PR TITLE
only import the webbrowser module when needed

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I'm using this great library with pyqt and when I want to freeze the files it complains the webbrowser module isn't available.

```
 File ":/flickrapi/tokencache.py", line 9, in <module>
 File "bootstrap.py", line 969, in _find_and_load
 File "bootstrap.py", line 958, in _find_and_load_unlocked
 File "bootstrap.py", line 664, in _load_unlocked
 File "bootstrap.py", line 634, in _load_backward_compatible
 File ":/flickrapi/auth.py", line 21, in <module>
 File "bootstrap.py", line 969, in _find_and_load
 File "bootstrap.py", line 956, in _find_and_load_unlocked
 ImportError: No module named 'webbrowser'
```
This is correct because my embedded application doesn't use, or have access, to a webbrowser. Considering that I don't need to launch a browser ever (already have the token from elsewhere) I suggest moving the import so it doesn't bother non-web apps.

**Comment by thijstriemstra** [comment]
@sybrenstuvel ping

**Comment by thijstriemstra** [comment]
Also successfully used requests-futures to make the requests call async. Included in PR.

**Comment by sybrenstuvel** [comment]
Please don't add unrelated features to existing pull requests. I've looked at Requests-Futures, and it requires Python >= 3.4. Even though I'd love to live in a world where everybody moved from Python 2 to 3, that's not the world we live in right now, so I can't drop Python 2 support just for this feature.

**Comment by sybrenstuvel** [comment]
Cherry-picked the original pull request in d5657153032d44d4375dd68e8ac80bfcf971debc

**Comment by thijstriemstra** [comment]
@sybrenstuvel thanks! can we have a new release?

**Comment by sybrenstuvel** [comment]
Yeah, will do that tomorrow after you're done sending more awesomeness in your pull requests 😎👍

**Comment by sybrenstuvel** [comment]
2.3 has been released.

**Comment by thijstriemstra** [comment]
Thanks!

**Pull request closed without merging**
