### PR TITLE
update changelog for 2.4.0

### LINKED ISSUE #103: Release 2.4
@sybrenstuvel can you release a new version on pypi?

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #103

### CODE REVIEW

**Comment by sybrenstuvel** [comment]
Thanks for writing this.

Personally I wouldn't mind simply calling this release 2.4. I reserve micro releases for really tiny things (like fixing my own mistakes while pushing a new version to pipy, or adding a file I forgot to package). Those changes you and the others did deserve a more prominent version increase!

**Comment by thijstriemstra** [comment]
@sybrenstuvel bump version to 2.4.

**Comment by thijstriemstra** [comment]
@sybrenstuvel thanks for the review. Would be great if you can release this version onto pypi.

**Comment by sybrenstuvel** [comment]
Released! https://pypi.python.org/pypi/flickrapi/2.4.0

**Pull request merged**
