### PR TITLE
properly include txt files (#101)

### LINKED ISSUE #101: README ... files in wrong location after installing
Currently if I install flickrapi with pip, the files LICENSE.txt, README.md, UPGRADING.txt, CHANGELOG.md will be located directly in the site-packages directory. I think this isn't desired, because if all apps would do that in this way, each update/install process will overwrite the files from each other.

I propose to copy this files inside the flickrapi folder, if necessary.

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #101

### CODE REVIEW

**Comment by sybrenstuvel** [comment]
Thanks!

**Comment by thijstriemstra** [comment]
No worries. @sybrenstuvel can you also put out new release/changelog/tag?

**Comment by sybrenstuvel** [comment]
Sure! Is the changelog up to date (i.e. do I only need to put the date in there)?

**Comment by thijstriemstra** [comment]
@sybrenstuvel there have been a couple of changes since the last release when looking at the commit log, if you can add those for a 2.3.1 section in changelog I think we're good to go.

**Comment by thijstriemstra** [comment]
ping @sybrenstuvel

**Pull request merged**
